server:
  port: 8090
auth:
  url: http://localhost:9001
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:h2:mem::databaseName
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  profiles:
    active:
      - "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${auth.url}/oauth2/introspect
          client-id: accounts-service
          client-secret: accounts-secret
        client:
          registration:
            loans-service:
              client-id: loans-service
              client-secret: loans-secret
              authorization-grant-type: client_credentials
              scope: service.read, service.write, internal.api
            opaque-service-client:
              client-id: secure-service
              client-secret: secure-secret
              authorization-grant-type: client_credentials
              scope: service.read, service.write, internal.api, introspection
          provider:
            loans-service:
              token-uri: ${auth.url}/oauth2/token
            opaque-service-client:
              token-uri: ${auth.url}/oauth2/token
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "loans microservice"
    version: "1.0.0"

logging:
  level:
    com:
      microservice:
        loans: DEBUG

