server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      - "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
