build:
  version: "2.0"

accounts:
  message: "Welcome to accounts microservice QA APIs"
  contactDetails:
    name: "Roshan - QA Lead"
    email: "roshan.qa@microservice.com"
  onCallSupport:
    - (555) 555-7890
    - (555) 523-7880