loans:
  message: "Welcome to loans microservice APIs"
  contactDetails:
    name: "Roshan - Developer"
    email: "roshan.dev@microservice.com"
  onCallSupport:
    - (555) 555-12234
    - (555) 523-12345
